feat: league_player
dreamscore-oss/openapi pull request #8
Opened 2024-03-18 12:31 UTC by sunnyfisch

2024-03-18 15:30 UTC, boostvolt requested changes

2024-03-18 15:30 UTC, boostvolt commented on dreamscore.yaml
> +          description: The information of the player
missing response content

2024-03-18 15:30 UTC, boostvolt commented on dreamscore.yaml
> +        - $ref: "#/components/parameters/playerId"
leagueId param is missing

2024-03-18 15:30 UTC, boostvolt commented on dreamscore.yaml
> +          description: The URL of the team's cover
we already have a club schema which should be used (coverUrl is no longer needed)

2024-03-18 15:30 UTC, boostvolt commented on dreamscore.yaml
> +      type: object
not required. because you defined properties below

2024-03-18 15:30 UTC, boostvolt commented on dreamscore.yaml
> -          description: The number of the player
we need those infos on the player preview because other endpoints depend on them

2024-03-18 15:30 UTC, boostvolt commented on dreamscore.yaml
> +                $ref: "#/components/schemas/playerPreview"
This should return infos visible on the new transfer screen on a player

2024-03-18 15:30 UTC, boostvolt commented on dreamscore.yaml
> +                $ref: "#/components/schemas/player"
On this endpoint we should return the player header infos visible in all tabs on a player. it includes portrait, name, club, user, etc.

2024-03-18 15:30 UTC, boostvolt commented on dreamscore.yaml
> +          type: integer
adjust according the endpoint needs as mentioned above

2024-03-19 07:39 UTC, sunnyfisch commented on dreamscore.yaml
> -          description: The number of the player
But if you need all this information, then you can get the player who has all the information in it.

2024-03-20 18:26 UTC, boostvolt commented
closed in favor of #9

2024-03-20 18:26 UTC, closed without merging